# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BAAppSessionExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BAAppSessionExample
  pod 'BAAppSessionClient', :path => '../'

  target 'BAAppSessionExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BAAppSessionExampleUITests' do
  # Pods for testing
  pod 'BAAppSessionServer', :path => '../'
  pod 'KIF'
  
end
